# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyStore.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='keyStore.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0ekeyStore.proto\"9\n\x10getRequestClient\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x18\n\x10\x63onsistencyLevel\x18\x02 \x01(\t\"H\n\x10putRequestClient\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t\x12\x18\n\x10\x63onsistencyLevel\x18\x03 \x01(\t\"+\n\x1a\x63oordinatorResponseMessage\x12\r\n\x05value\x18\x01 \x01(\t\"3\n\x1b\x63oordinatorExceptionMessage\x12\x14\n\x0c\x65rrorMessage\x18\x01 \x01(\t\"\x19\n\ngetMessage\x12\x0b\n\x03key\x18\x01 \x01(\r\";\n\nputMessage\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\")\n\x10returnPutMessage\x12\x15\n\rmessageString\x18\x01 \x01(\t\"F\n\x10returnGetMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08notFound\x18\x03 \x01(\x08\";\n\x12replicaInitMessage\x12\x11\n\tipAddress\x18\x01 \x01(\t\x12\x12\n\nportNumber\x18\x02 \x01(\r\"\x80\x04\n\x0eReplicaMessage\x12(\n\x0bget_request\x18\x01 \x01(\x0b\x32\x11.getRequestClientH\x00\x12(\n\x0bput_request\x18\x02 \x01(\x0b\x32\x11.putRequestClientH\x00\x12;\n\x14\x63oordinator_response\x18\x03 \x01(\x0b\x32\x1b.coordinatorResponseMessageH\x00\x12=\n\x15\x63oordinator_exception\x18\x04 \x01(\x0b\x32\x1c.coordinatorExceptionMessageH\x00\x12\"\n\x0bget_message\x18\x05 \x01(\x0b\x32\x0b.getMessageH\x00\x12\"\n\x0bput_message\x18\x06 \x01(\x0b\x32\x0b.putMessageH\x00\x12/\n\x12return_put_message\x18\x07 \x01(\x0b\x32\x11.returnPutMessageH\x00\x12/\n\x12return_get_message\x18\x08 \x01(\x0b\x32\x11.returnGetMessageH\x00\x12\x33\n\x14replica_init_message\x18\t \x01(\x0b\x32\x13.replicaInitMessageH\x00\x12\x15\n\rsrc_replicaID\x18\n \x01(\t\x12\x15\n\rdst_replicaID\x18\x0b \x01(\tB\x11\n\x0freplica_messageb\x06proto3')
)




_GETREQUESTCLIENT = _descriptor.Descriptor(
  name='getRequestClient',
  full_name='getRequestClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='getRequestClient.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consistencyLevel', full_name='getRequestClient.consistencyLevel', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=75,
)


_PUTREQUESTCLIENT = _descriptor.Descriptor(
  name='putRequestClient',
  full_name='putRequestClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='putRequestClient.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='putRequestClient.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consistencyLevel', full_name='putRequestClient.consistencyLevel', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=149,
)


_COORDINATORRESPONSEMESSAGE = _descriptor.Descriptor(
  name='coordinatorResponseMessage',
  full_name='coordinatorResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='coordinatorResponseMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=194,
)


_COORDINATOREXCEPTIONMESSAGE = _descriptor.Descriptor(
  name='coordinatorExceptionMessage',
  full_name='coordinatorExceptionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='coordinatorExceptionMessage.errorMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=247,
)


_GETMESSAGE = _descriptor.Descriptor(
  name='getMessage',
  full_name='getMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='getMessage.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=274,
)


_PUTMESSAGE = _descriptor.Descriptor(
  name='putMessage',
  full_name='putMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='putMessage.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='putMessage.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='putMessage.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=335,
)


_RETURNPUTMESSAGE = _descriptor.Descriptor(
  name='returnPutMessage',
  full_name='returnPutMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageString', full_name='returnPutMessage.messageString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=378,
)


_RETURNGETMESSAGE = _descriptor.Descriptor(
  name='returnGetMessage',
  full_name='returnGetMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='returnGetMessage.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='returnGetMessage.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notFound', full_name='returnGetMessage.notFound', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=450,
)


_REPLICAINITMESSAGE = _descriptor.Descriptor(
  name='replicaInitMessage',
  full_name='replicaInitMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ipAddress', full_name='replicaInitMessage.ipAddress', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='portNumber', full_name='replicaInitMessage.portNumber', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=511,
)


_REPLICAMESSAGE = _descriptor.Descriptor(
  name='ReplicaMessage',
  full_name='ReplicaMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_request', full_name='ReplicaMessage.get_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='put_request', full_name='ReplicaMessage.put_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinator_response', full_name='ReplicaMessage.coordinator_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinator_exception', full_name='ReplicaMessage.coordinator_exception', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_message', full_name='ReplicaMessage.get_message', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='put_message', full_name='ReplicaMessage.put_message', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_put_message', full_name='ReplicaMessage.return_put_message', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_get_message', full_name='ReplicaMessage.return_get_message', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replica_init_message', full_name='ReplicaMessage.replica_init_message', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_replicaID', full_name='ReplicaMessage.src_replicaID', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_replicaID', full_name='ReplicaMessage.dst_replicaID', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='replica_message', full_name='ReplicaMessage.replica_message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=514,
  serialized_end=1026,
)

_REPLICAMESSAGE.fields_by_name['get_request'].message_type = _GETREQUESTCLIENT
_REPLICAMESSAGE.fields_by_name['put_request'].message_type = _PUTREQUESTCLIENT
_REPLICAMESSAGE.fields_by_name['coordinator_response'].message_type = _COORDINATORRESPONSEMESSAGE
_REPLICAMESSAGE.fields_by_name['coordinator_exception'].message_type = _COORDINATOREXCEPTIONMESSAGE
_REPLICAMESSAGE.fields_by_name['get_message'].message_type = _GETMESSAGE
_REPLICAMESSAGE.fields_by_name['put_message'].message_type = _PUTMESSAGE
_REPLICAMESSAGE.fields_by_name['return_put_message'].message_type = _RETURNPUTMESSAGE
_REPLICAMESSAGE.fields_by_name['return_get_message'].message_type = _RETURNGETMESSAGE
_REPLICAMESSAGE.fields_by_name['replica_init_message'].message_type = _REPLICAINITMESSAGE
_REPLICAMESSAGE.oneofs_by_name['replica_message'].fields.append(
  _REPLICAMESSAGE.fields_by_name['get_request'])
_REPLICAMESSAGE.fields_by_name['get_request'].containing_oneof = _REPLICAMESSAGE.oneofs_by_name['replica_message']
_REPLICAMESSAGE.oneofs_by_name['replica_message'].fields.append(
  _REPLICAMESSAGE.fields_by_name['put_request'])
_REPLICAMESSAGE.fields_by_name['put_request'].containing_oneof = _REPLICAMESSAGE.oneofs_by_name['replica_message']
_REPLICAMESSAGE.oneofs_by_name['replica_message'].fields.append(
  _REPLICAMESSAGE.fields_by_name['coordinator_response'])
_REPLICAMESSAGE.fields_by_name['coordinator_response'].containing_oneof = _REPLICAMESSAGE.oneofs_by_name['replica_message']
_REPLICAMESSAGE.oneofs_by_name['replica_message'].fields.append(
  _REPLICAMESSAGE.fields_by_name['coordinator_exception'])
_REPLICAMESSAGE.fields_by_name['coordinator_exception'].containing_oneof = _REPLICAMESSAGE.oneofs_by_name['replica_message']
_REPLICAMESSAGE.oneofs_by_name['replica_message'].fields.append(
  _REPLICAMESSAGE.fields_by_name['get_message'])
_REPLICAMESSAGE.fields_by_name['get_message'].containing_oneof = _REPLICAMESSAGE.oneofs_by_name['replica_message']
_REPLICAMESSAGE.oneofs_by_name['replica_message'].fields.append(
  _REPLICAMESSAGE.fields_by_name['put_message'])
_REPLICAMESSAGE.fields_by_name['put_message'].containing_oneof = _REPLICAMESSAGE.oneofs_by_name['replica_message']
_REPLICAMESSAGE.oneofs_by_name['replica_message'].fields.append(
  _REPLICAMESSAGE.fields_by_name['return_put_message'])
_REPLICAMESSAGE.fields_by_name['return_put_message'].containing_oneof = _REPLICAMESSAGE.oneofs_by_name['replica_message']
_REPLICAMESSAGE.oneofs_by_name['replica_message'].fields.append(
  _REPLICAMESSAGE.fields_by_name['return_get_message'])
_REPLICAMESSAGE.fields_by_name['return_get_message'].containing_oneof = _REPLICAMESSAGE.oneofs_by_name['replica_message']
_REPLICAMESSAGE.oneofs_by_name['replica_message'].fields.append(
  _REPLICAMESSAGE.fields_by_name['replica_init_message'])
_REPLICAMESSAGE.fields_by_name['replica_init_message'].containing_oneof = _REPLICAMESSAGE.oneofs_by_name['replica_message']
DESCRIPTOR.message_types_by_name['getRequestClient'] = _GETREQUESTCLIENT
DESCRIPTOR.message_types_by_name['putRequestClient'] = _PUTREQUESTCLIENT
DESCRIPTOR.message_types_by_name['coordinatorResponseMessage'] = _COORDINATORRESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['coordinatorExceptionMessage'] = _COORDINATOREXCEPTIONMESSAGE
DESCRIPTOR.message_types_by_name['getMessage'] = _GETMESSAGE
DESCRIPTOR.message_types_by_name['putMessage'] = _PUTMESSAGE
DESCRIPTOR.message_types_by_name['returnPutMessage'] = _RETURNPUTMESSAGE
DESCRIPTOR.message_types_by_name['returnGetMessage'] = _RETURNGETMESSAGE
DESCRIPTOR.message_types_by_name['replicaInitMessage'] = _REPLICAINITMESSAGE
DESCRIPTOR.message_types_by_name['ReplicaMessage'] = _REPLICAMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

getRequestClient = _reflection.GeneratedProtocolMessageType('getRequestClient', (_message.Message,), dict(
  DESCRIPTOR = _GETREQUESTCLIENT,
  __module__ = 'keyStore_pb2'
  # @@protoc_insertion_point(class_scope:getRequestClient)
  ))
_sym_db.RegisterMessage(getRequestClient)

putRequestClient = _reflection.GeneratedProtocolMessageType('putRequestClient', (_message.Message,), dict(
  DESCRIPTOR = _PUTREQUESTCLIENT,
  __module__ = 'keyStore_pb2'
  # @@protoc_insertion_point(class_scope:putRequestClient)
  ))
_sym_db.RegisterMessage(putRequestClient)

coordinatorResponseMessage = _reflection.GeneratedProtocolMessageType('coordinatorResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATORRESPONSEMESSAGE,
  __module__ = 'keyStore_pb2'
  # @@protoc_insertion_point(class_scope:coordinatorResponseMessage)
  ))
_sym_db.RegisterMessage(coordinatorResponseMessage)

coordinatorExceptionMessage = _reflection.GeneratedProtocolMessageType('coordinatorExceptionMessage', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATOREXCEPTIONMESSAGE,
  __module__ = 'keyStore_pb2'
  # @@protoc_insertion_point(class_scope:coordinatorExceptionMessage)
  ))
_sym_db.RegisterMessage(coordinatorExceptionMessage)

getMessage = _reflection.GeneratedProtocolMessageType('getMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETMESSAGE,
  __module__ = 'keyStore_pb2'
  # @@protoc_insertion_point(class_scope:getMessage)
  ))
_sym_db.RegisterMessage(getMessage)

putMessage = _reflection.GeneratedProtocolMessageType('putMessage', (_message.Message,), dict(
  DESCRIPTOR = _PUTMESSAGE,
  __module__ = 'keyStore_pb2'
  # @@protoc_insertion_point(class_scope:putMessage)
  ))
_sym_db.RegisterMessage(putMessage)

returnPutMessage = _reflection.GeneratedProtocolMessageType('returnPutMessage', (_message.Message,), dict(
  DESCRIPTOR = _RETURNPUTMESSAGE,
  __module__ = 'keyStore_pb2'
  # @@protoc_insertion_point(class_scope:returnPutMessage)
  ))
_sym_db.RegisterMessage(returnPutMessage)

returnGetMessage = _reflection.GeneratedProtocolMessageType('returnGetMessage', (_message.Message,), dict(
  DESCRIPTOR = _RETURNGETMESSAGE,
  __module__ = 'keyStore_pb2'
  # @@protoc_insertion_point(class_scope:returnGetMessage)
  ))
_sym_db.RegisterMessage(returnGetMessage)

replicaInitMessage = _reflection.GeneratedProtocolMessageType('replicaInitMessage', (_message.Message,), dict(
  DESCRIPTOR = _REPLICAINITMESSAGE,
  __module__ = 'keyStore_pb2'
  # @@protoc_insertion_point(class_scope:replicaInitMessage)
  ))
_sym_db.RegisterMessage(replicaInitMessage)

ReplicaMessage = _reflection.GeneratedProtocolMessageType('ReplicaMessage', (_message.Message,), dict(
  DESCRIPTOR = _REPLICAMESSAGE,
  __module__ = 'keyStore_pb2'
  # @@protoc_insertion_point(class_scope:ReplicaMessage)
  ))
_sym_db.RegisterMessage(ReplicaMessage)


# @@protoc_insertion_point(module_scope)
